config/routes.rb
Barterville::Application.routes.draw do

  root :to => 'home#index'

  resources :users
  resources :products do
    collection do
      get 'search'
      get 'alert'
    end
    member do
      get 'barter'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  get '/requests' => 'requests#index'
  post '/action' => 'requests#action'

  get '/accept' => 'requests#accept'
  get '/reject' => 'requests#reject'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  photo       :string(255)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
	belongs_to :user
	has_many :requests
  	mount_uploader :photo, PhotoUploader

    def self.text_search(query)
       self.where("name @@ :q or description @@ :q", :q => query)
  	end

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id          :integer          not null, primary key
#  product_id  :integer
#  buyer_id    :integer
#  owner_id    :integer
#  done        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  exchange_id :integer
#

class Request < ActiveRecord::Base
	belongs_to :product
  belongs_to :exchange, :class_name => 'Product', :foreign_key => :exchange_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  password_digest :string(255)
#  photo           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string(255)
#

class User < ActiveRecord::Base
	has_secure_password
	has_many :products
  	mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user
  # after_filter :check_alerts
  private
  def authenticate_user
    if session[:name]
      @authenticated_user = User.where(:name => session[:name]).first
    else
      @authenticated_user = nil
    end
  end
  # def check_alerts
  #   if  Request.where(:owner_id => @authenticated_user, :done => false).present?
  #     redirect_to alert_products_path
  #   end
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	def index
		@products = Product.order(:name).page(params[:page])
	end
	def new
		@product = Product.new
	end
	def create
		@product = Product.new(params[:product])

		if @product.save

			User.find(session[:id]).products << @product
			redirect_to root_path
		else
			render :new
		end
	end
	def show
		@product = Product.find(params[:id])
	end
	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to @product
		else
			render :edit
		end
	end
	def edit
		@product = Product.find(params[:id])
	end
	def destroy
		product = Product.find(params[:id])
    	product.delete
    	redirect_to user_path(User.find(session[:id]))
	end
	def search
		query = params[:query]
		if query.present?
			@products = Product.text_search(query).page(params[:page])
		else
			@products = Product.order(query).page(params[:page])
		end
	end
	def barter
		exchange_id = params[:exchange_id]
		product_id = params[:id]
		product = Product.find(product_id)
		owner = product.user
		buyer = @authenticated_user
		request = Request.new(:buyer_id => buyer.id, :owner_id => owner.id, :product_id => product_id, :done => false, :exchange_id => exchange_id)
		if request.save
			Notifications.trade(buyer.name).deliver
		else
			render :show
		end
	end
	def alert

	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    user = @authenticated_user
    @requests = Request.where(:owner_id => @authenticated_user, :done => false)
  end
  def action

    action = params[:commit]

    @request_id = params[:request]

    r = Request.find(@request_id)
    @product_id = r.product_id

    r.done = true

    if action == 'accept'
      p = Product.find(r.product_id)
      p.user_id = r.buyer_id
      p2 = Product.find(r.exchange_id)
      p2.user_id = r.owner_id
      @action = 'accept'
      p.save
      p2.save
      Notifications.confirmation(@authenticated_user.name,p2.name).deliver
      #cleaning up, delete all items pertaining to the trades in other requests
      Request.where(:product_id => r.product_id).delete_all
      # Request.where(:product_id => r.exchange_id).delete_all
      # Request.where(:exchange_id => r.product_id).delete_all
      # Request.where(:exchange_id => r.exchange_id).delete_all
    else
      @action = 'reject'
    end
    r.save


  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	skip_before_filter :authenticate_user #Avoids a redirect loop if user isn't authenticated.

	def new
	end
	def create
		user = User.find_by_name(params[:name])
		if user && user.authenticate(params[:password])
			session[:name] = user.name
			session[:id] = user[:id]
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		reset_session #Session was maintaining the same :id even after logout. This will reset it all.
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.order(:name).page(params[:page])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])

		if @user.save
			name = params[:user][:name]
    		session[:name] = name
			session[:id] = @user[:id]
			redirect_to root_path
		else
			render :new
		end
	end
	def show
		@user = User.find(params[:id])
		@products = Product.where(:user_id => params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to @user
		else
			render :edit
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def destroy
		user = User.find(params[:id])
    	user.delete
    	redirect_to user_path(User.find(session[:id]))
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def show_login_or_logout_link
		if @authenticated_user
			link_to "Logout", logout_path
		else
			link_to "Login", login_path
		end
	end
end

app/views/home/index.html.erb
<h1>Welcome to Barterville</h1>
<img src="http://farm2.staticflickr.com/1149/3174174175_6d9e69aa9d_o.jpg">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barterville</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row">
	  <div class="span12">
	  	<div class="navbar navbar-inverse">
		  <div class="navbar-inner">
		    <a class="brand" href="#">Barterville</a>
		    <ul class="nav">
		      <li class="active"><%= link_to "Home", root_path %></li>

		      <li><%= link_to @authenticated_user.name, requests_path  if !@authenticated_user.nil? %></li>
		      <li><%= link_to "Users", users_path if !@authenticated_user.nil? %></li>
		      <li><%= link_to "Create New User", new_user_path if @authenticated_user.nil? %></li>
		      <li><%= link_to "Products", products_path if !@authenticated_user.nil? %></li>
		      <li><%= link_to "Create New Product", new_product_path if !@authenticated_user.nil? %></li>
		      <li><%= show_login_or_logout_link %></li>
		    </ul>
		  </div>
		</div>
	  </div>
	</div>
	<div class="row">
	  <div class="span3">
	  	<%= render 'shared/search' %>
	  </div>
	  <div class="span9" id="main-content"><%= yield %></div>
	</div>
	<div class="row">
	  <div class="span12"></div>
	</div>
</div>
</body>
</html>

app/views/notifications/confirmation.text.erb
Hi <%= @user %>, your offer for <%= @item %> has been accepted!.

app/views/notifications/trade.text.erb
Hi <%= @greeting %>, someone wants to trade with you!

app/views/products/_display.html.erb
<ul class='user_products'>
<% products.each do |product| %>
	<li><%= link_to image_tag(product.photo), product_path(product) %>
    <i class="icon-plus"></i><%= link_to product.name, product_path(product) %></li>
<% end %>
</ul>
<%= paginate products %>

app/views/products/_form.html.erb
<%= form_for @product do |t| %>
	<%= t.label :name %>
	<%= t.text_field :name %>
	<%= t.label :description %>
	<%= t.text_area :description, :rows => 10 %>

    <label>product photo</label>
    <%= image_tag(@product.photo.thumb) if @product.photo? %>
    <%= t.file_field :photo %>
    <%= t.hidden_field :photo_cache %>
    <%= t.text_field :remote_photo_url %>

	<%= t.submit %>
<% end %>

app/views/products/barter.js.erb
alert('message sent!');

app/views/products/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<div id="product_content">
	<h1>All Products</h1>

	<%= render :partial => 'display', :locals => {:products => @products} %>
</div>

app/views/products/new.html.erb
<h1>Create New Product</h1>

<%= render 'form' %>

app/views/products/search.js.erb
$('#main-content').empty();

$('#main-content').append("<h1>Search Results</h1><%=j render :partial => 'display', :locals => {:products => @products} %>");

app/views/products/show.html.erb
<div class='user_products'>
  <li><%= image_tag(@product.photo.thumb) if @product.photo? %>
  <%= @product.name %><br>
  Owner: <%= link_to @product.user.name, user_path(@product.user) %><br>
  <%= @product.description %></li>
</div>



<!-- BARTER BUTTON -->
<% if !(@authenticated_user == @product.user) %>
	<div id="barter-dropdown">	<!-- AJAX request -->
  		<%= form_tag barter_product_path, :id => 'barterbutton',:method => :get, :remote => true do %>
  	
	    <%= select_tag :exchange_id, options_from_collection_for_select(@authenticated_user.products, "id", "name") %>
	    <%= submit_tag 'Send Request!', :class => 'btn btn-success' %>
  		<% end %>
  	</div>
<% end %>

<%= link_to "Edit product", edit_product_path(@product) if @authenticated_user.id == @product.user_id %>
<br>

<%= link_to "Delete product", product_path(@product), :method => :delete, :confirm => "Are you sure?" if @authenticated_user.id == @product.user_id %>

app/views/requests/action.js.erb
<% if @action == "reject" %>
	$('#div<%=@request_id %>').empty()
<% elsif @action == "accept" %>
	$('.div<%=@product_id %>').empty()
<% end %>

app/views/requests/index.html.erb
<h1>My Profile - <%= @authenticated_user.name %></h1>
<hr>
<h3>Pending Requests</h3>
<h3><%= "You have no pending requests." if @requests.empty? %></h3>
<ul>
<% @requests.each do |r| %>

<div class=<%= "div#{r.product_id}"%> id=<%= "div#{r.id}"%>>
<li class='requests'>  <%= link_to image_tag(r.exchange.photo), r.exchange %>

    <i class="icon-plus"></i><%= link_to r.exchange.name, r.exchange %> <br>
    <i class="icon-user"></i><%= link_to User.find(r.buyer_id).name, User.find(r.buyer_id) %> <br>
    <i class="icon-minus"></i><%= link_to r.product.name, r.product %>
  <%= form_tag '/action', :remote => true do %>
    <%= hidden_field_tag :request, r.id %>
    <%= submit_tag 'accept', :class => 'btn-success' %>
    <%= submit_tag 'reject', :class => 'btn-danger' %>
    </li>
  <% end %>
     </div>

<% end %>
</ul>
<div class='clear'></div>
<h3>My Products</h3>
<%= render :partial => 'products/display', :locals => {:products => Product.where(:user_id => @authenticated_user.id).page(params[:page])} %>

app/views/session/new.html.erb
<%= form_tag '/login' do %>
    <%= label_tag 'Name' %>
    <%= text_field_tag 'name' %>
    <%= label_tag 'Password' %>
    <%= password_field_tag 'password' %>
    <br>
    <%= submit_tag 'Login' %>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag search_products_path, :id => 'searchform',:method => :get, :remote => true do %>
  <%= text_field_tag 'query' %>
  <%= submit_tag 'Search Products', :class => 'btn btn-success' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:multipart => true} do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.label :email %>
  <%= t.text_field :email %>
  <%= t.label :password %>
  <%= t.password_field :password %>
  <%= t.label :password_confirmation %>
  <%= t.password_field :password_confirmation %>

    <label>My photo</label>
    <%= image_tag(@user.photo.thumb) if @user.photo? %>
    <%= t.file_field :photo %>
    <%= t.hidden_field :photo_cache %>
    <%= t.text_field :remote_photo_url %>
  <%= t.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul id="user_index">
<% @users.each do |user| %>
	<li>
    <%= link_to image_tag(user.photo.thumb), user_path(user) %>
    <div class='id'><i class="icon-user"></i> <%= link_to user.name, user_path(user) %></div>

  </li>
<% end %>
</ul>

<%= paginate @users %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div id="user_show">
  <%= image_tag(@user.photo.thumb) if @user.photo? %>

<i class="icon-user"></i><%= @user.name %><br>
<%= @user.email %>
<%= link_to "edit", edit_user_path(@user) if @authenticated_user == @user %>
</div>

<ul class='user_products'>
<% @products.each do |product| %>
  <li><%= link_to image_tag(product.photo), product_path(product) %>
	<i class="icon-plus"></i><%= link_to product.name, product_path(product) %></li>
<% end %>
</ul>